### PR TITLE
Removing wrapping div

### PR DESCRIPTION
**Pull request by readeral**
Can I propose the removal of the wrapping `<div>` in favour of a fragment, as it's stopping the `<input>` from being laid out on on css grid (and any other CSS descendant-reliant situation).

I don't know what other implications there might be for removing the wrapping div, so happy to have this pull request rejected. I just have found that I couldn't use this library within my grid layout without even more wrapping `<div>`s because any grid CSS I was passing through props wasn't ultimately able to be applied to the input.

## Screenshots (if relevant):

### CODE REVIEW

**Comment by adrians5j** [comment]
This is great @readeral !
Not sure how the `div` ended up here. Fragment is a much better solution.

I can merge this, but before I do that, if you want, you can add yourself as a contributor by running the `yarn contributors:add` command.

Let me know when it's OK to merge this one.

Thanks again!

**Comment by readeral** [comment]
That was the longest yarn install experience I've had for a while! Done :)

**Comment by adrians5j** [comment]
Thanks a lot, @readeral, I just gotta check why Cypress is failing in Travis and will release this.

😦😩

**Pull request merged**
